CREATE DATABASE IF NOT EXISTS JWT_DB;
USE JWT_DB;

-- DROP DATABASE jwt_db

CREATE TABLE IF NOT EXISTS Usuario(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    nombre_2 VARCHAR(100),
    app_paterno VARCHAR(100) NOT NULL,
    app_materno VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);

SELECT * FROM Usuario;